repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.0"
    hooks:
      - id: ruff
        args: ["--exclude=.venv"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-ast
      - id: end-of-file-fixer
        exclude: rapidocr_openvino/ch_ppocr_v3_rec/en_dict.txt
      - id: trailing-whitespace
        exclude: rapidocr_openvino/ch_ppocr_v3_rec/en_dict.txt
